import re
import frappe
from bs4 import BeautifulSoup
from .integrations.twilio import send_whatsapp_message


def strip_html_tags(text: str) -> str:
	"""Strip HTML tags generated by Raven rich text editor."""
	if not text:
		return ""
	soup = BeautifulSoup(str(text), "html.parser")
	return soup.get_text(separator=" ").strip()


def extract_phone_from_channel(channel_id: str) -> str | None:
	"""Scan recent channel messages for a valid WhatsApp phone number."""
	messages = frappe.get_all(
		"Raven Message",
		filters={"channel": channel_id},
		fields=["text", "owner"],
		order_by="creation desc",
		limit=20,
	)

	phone_pattern = re.compile(r"\+?\d{10,15}")

	for msg in messages:
		text = msg.get("text") or ""
		if "WhatsApp -" in text or "whatsapp:" in text:
			match = phone_pattern.search(text)
			if match:
				phone = match.group(0)
				return phone if phone.startswith("+") else f"+{phone}"

	return frappe.db.get_value(
		"Sales Order",
		filters={"custom_raven_channel_id": channel_id, "docstatus": ["<", 2]},
		fieldname="contact_phone",
	)


def on_raven_message_created(doc, method=None):
	"""Hook triggered when a message is inserted in Raven."""
	# 1. Ignore messages flagged as inbound from WhatsApp
	if getattr(doc.flags, "from_whatsapp", False):
		return

	raw_text = getattr(doc, "text", "") or getattr(doc, "content", "")
	clean_text = strip_html_tags(raw_text)

	# 2. Skip empty messages, bot echoes, or incoming webhook proxies
	if not clean_text:
		return

	if clean_text.startswith("WhatsApp -") or "whatsapp:" in clean_text.lower():
		return

	channel_id = getattr(doc, "channel", None) or getattr(doc, "channel_id", None)
	if not channel_id:
		return

	# 3. Resolve customer phone number
	customer_phone = extract_phone_from_channel(channel_id)
	if not customer_phone:
		frappe.log_error(title="Raven Outbound Skip", message=f"No recipient phone found for channel: {channel_id}")
		return

	# 4. Dispatch clean text via Twilio
	try:
		sid = send_whatsapp_message(to=customer_phone, body=clean_text)
		print(f"[RAVEN OUTBOUND SUCCESS] Sent '{clean_text}' to {customer_phone} (SID: {sid})")
	except Exception as e:
		frappe.log_error(title="Raven Outbound Error", message=str(e))
		print(f"[RAVEN OUTBOUND ERROR] {e}")
